apps/restaurants/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (RestaurantListView,RestaurantDetailView,
                    FoodListView,FoodDetailView,RestaurantReview,
                    FoodTryIt,RestaurantLike, ReviewDelete)


urlpatterns = [
    path('',RestaurantListView.as_view(),name="restaurants"),
    path('restaurant/<slug:slug>/',RestaurantDetailView.as_view(),name="restaurant_detail"),
    path('foods/',FoodListView.as_view(),name='foods'),
    path('food/<str:restaurant>/food/<str:name>/',FoodDetailView.as_view(),name='food'),
    path('food/try-it/<int:pk>/',FoodTryIt.as_view(),name='food-try'),
    path('restaurant/like/<slug:slug>/',RestaurantLike.as_view(),name='restaurant-like'),
    path('restaurant/<slug:slug>/review',RestaurantReview.as_view(),name='restaurant-review'),
    path('restaurant/reviews/<int:pk>/delete/',ReviewDelete.as_view(),name='review-delete'),    
] 

iraf/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
import apps.blog.views

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from django.contrib.sitemaps.views import sitemap
from apps.blog.sitemaps import PostSitemap, CategorySitemap
from apps.restaurants.sitemaps import FoodSitemap, RestaurantSitemap

sitemaps = {
		"posts": PostSitemap,
        "categories": CategorySitemap,
        "restaurants": RestaurantSitemap,
        "food": FoodSitemap
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('apps.user.urls')),

    path('restaurants/',include('apps.restaurants.urls')),

    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('pages/', include(wagtail_urls)),
    path('robots.txt', apps.blog.views.RobotsView.as_view()),
    
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
						name='django.contrib.sitemaps.views.sitemap')
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/restaurants/models.py
from django.db import models
from django.utils.text import slugify
from django.http import HttpResponseForbidden
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse

      
class Restaurant(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(max_length=300,unique=True,blank=True,primary_key=True)
    like = models.ManyToManyField(User,related_name='+',blank=True)
    description = models.TextField(blank=True,null=True)
    location = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    contact = models.CharField(max_length=255)
    about = models.CharField(max_length=255)
    rating = models.FloatField(default=0.0,null=True,blank=True)
    reviews = models.ManyToManyField('Review',related_name='reviews',blank=True)
    image = models.ImageField(verbose_name="restaurant_image", upload_to='media/restaurants/', default=None,null=True,blank=True,height_field=None, width_field=None)
    date = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['rating']
        
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Restaurant, self).save(*args, **kwargs)
        
    def perform_review(self,user,review,restaurant):
        has_reviewed = Review.objects.filter(review_user=user,restaurant=restaurant)
        if not has_reviewed:
            review = Review.objects.create(review_user=user,rating=review['rating'],description=review['description'],restaurant=restaurant)
            review.save()
            restaurant.reviews.add(review)
            if restaurant.rating == 0.0:
                restaurant.rating = review.rating 
                restaurant.save()
            else:
                restaurant.rating = (restaurant.rating + review.rating)/2
                restaurant.save()
            return restaurant
        else:
           return HttpResponseForbidden('you have review this restaurant',status=403)
    @property
    def get_absolute_url(self):
        return reverse("restaurant_detail", kwargs={"slug": self.slug})
    
    def __str__(self):
        return self.name
    
    
        
class FoodCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    
class Food(models.Model):
    name = models.CharField(max_length=255,unique=False)
    slug = models.SlugField(max_length=300,unique=True,blank=True)
    image = models.ImageField(verbose_name="food_image", upload_to='media/foods/', default=None,null=True,blank=True,height_field=None, width_field=None)
    restaurant = models.ForeignKey(Restaurant,related_name='restaurants',null=True,on_delete=models.CASCADE)
    price = models.PositiveSmallIntegerField()
    description = models.TextField(null=True, blank=True)
    discount_price = models.PositiveSmallIntegerField()
    categories = models.ManyToManyField(FoodCategory, related_name='category',blank=True)
    star = models.FloatField(default=0.0,null=True, blank=True)
    try_it = models.ManyToManyField(User, related_name='try_it',blank=True)
    purchase = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    
    
    class Meta:
        ordering = ['-date']
        
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Food, self).save(*args, **kwargs)
    
    @property
    def get_absolute_url(self):
        return reverse("food",kwargs={'name':self.name,'restaurant':self.restaurant})
        
    def __str__(self):
        return self.name
    
    @property
    def has_purchased(self):
        return self.purchase + 1
    
    
class Review(models.Model):
    review_user = models.ForeignKey(User,on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
    description = models.CharField(max_length=200,null=True)
    active = models.BooleanField(default=True)
    restaurant = models.ForeignKey(Restaurant,on_delete=models.CASCADE,related_name="restaurantreview",null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['rating',]
    
    def __str__(self):
        return f"{self.review_user} review for {self.restaurant}"
  

    

apps/restaurants/forms.py
from django import forms 
from .models import Review

class RestaurantReviewForm(forms.ModelForm):
    class Meta:
        model = Review 
        fields = ['rating', 'description']
        
        

    

apps/restaurants/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.views import View 
from django.contrib import messages
from django.views.generic.edit import DeleteView

from .models import Review, Restaurant, Food 
from .forms import RestaurantReviewForm


class RestaurantListView(View):
    def get(self, request):
        restaurants = Restaurant.objects.all()
        page = Paginator(restaurants,10)
        page_number = request.GET.get('page')
        page_obj = page.get_page(page_number)
        context = {
            'restaurants': restaurants,
            'page_obj': page_obj,
        }
        return render(request,'restaurant/restaurant-list.html', context)


class RestaurantDetailView(View):
    def get(self,request,slug,*args,**kwargs):
        restaurant = get_object_or_404(Restaurant,slug=slug)
        foods = Food.objects.filter(restaurant=restaurant)
        reviews = Review.objects.filter(restaurant=restaurant)
        paginator = Paginator(reviews,5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        
        five = Review.objects.filter(restaurant=restaurant,rating=5)
        four = Review.objects.filter(restaurant=restaurant,rating=4)
        three = Review.objects.filter(restaurant=restaurant,rating=3)
        two = Review.objects.filter(restaurant=restaurant,rating=2)
        one = Review.objects.filter(restaurant=restaurant,rating=1)
            
       
        context = {
            'restaurant':restaurant,
            'foods': foods,
            'reviews': reviews,
            'page_number':page_number,
            'page_obj':page_obj,
            'one': one,
            'two':two,
            'three':three,
            'four': four,
            'five':five
        }
        return render(request,'restaurant/restaurant.html', context)
    


class FoodListView(View):
    def get(self, request):
        foods = Food.objects.all()
        paginator = Paginator(foods,20)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
            
        context = {
            'foods':foods,
            'page_number': page_number,
            'page_obj': page_obj,
        }
        
        return render(request, 'restaurant/food-list.html',context)
    

class FoodDetailView(View):
    def get(self,request,name,restaurant):
        food = get_object_or_404(Food, name=name, restaurant=restaurant)
        categories = food.categories.all()
        
        context = {
            'categories': categories,
            'food': food,
        }   

        return render(request,'restaurant/food-detail.html',context)


class RestaurantReview(LoginRequiredMixin,View):
    def post(self,request,slug,*args,**kwargs):
        restaurant = get_object_or_404(Restaurant,slug=slug)
        form = RestaurantReviewForm(request.POST)
        
        user = request.user
        review_check = Review.objects.filter(review_user=user,restaurant=restaurant)

        
        if review_check:
            return HttpResponse('You have review this restaurant before')
    
        if form.is_valid():
            restaurant.perform_review(user=request.user,review=form.cleaned_data,restaurant=restaurant)
            return HttpResponse("Your review has been committed")
        else:
            return HttpResponse('Form not valid')
    
    
class FoodTryIt(LoginRequiredMixin,View):  
    def post(self, request,pk,*args,**kwargs):
        food = get_object_or_404(Food, pk=pk)
        user = request.user
        if user in food.try_it.all():
            food.try_it.remove(user)
            return HttpResponse('removed')
        
        else:
            food.try_it.add(user)
            return HttpResponse('added')

    
class RestaurantLike(LoginRequiredMixin,View):
    def post(self, request,slug,*args,**kwargs):
        restaurant = get_object_or_404(Restaurant, slug=slug)
        user = request.user
        
        if user in restaurant.like.all():
            restaurant.like.remove(user)
            likes = len(restaurant.like.all())
            messages.success(request,likes)
            return HttpResponse('unliked')
        else:
            restaurant.like.add(user)
            likes = len(restaurant.like.all())
            messages.success(request,likes)
            return HttpResponse('Liked')
        
class ReviewDelete(LoginRequiredMixin,View):
    def post(self, request,pk,*args,**kwargs):
        
        review = get_object_or_404(Review, pk=pk,review_user=request.user)
        restaurant = review.restaurant.slug
        review.delete()
        return redirect('restaurant_detail',restaurant)

apps/restaurants/templates/restaurant/food-aside.html
<aside
    class="transform top-0 right-0 w-full md:w-2/5 shadow-2xl bg-white fixed h-full overflow-auto ease-in-out transition-all duration-300 z-30 translate-x-full"
    @click="overlay=false">
    <div class="p-8">
        <button class="bg-gray-200 py-2 px-6 rounded-full" id="close-side-panel" @click="overlay=false"><i
                class="fas fa-times"></i></button>
        <main class="text-center">
            <img src="images/pizza.png" alt="burger" class="w-56 mx-auto mt-16 mb-8">
            <span class="font-bold text-3xl">{{food.name}}</span>
            <span class="block text-gray-600 text-sm">Pepperoni, Mozzarella, Tomato sauce {{food.pk}}</span>
            <span class="block text-custom-yellow mt-6 font-bold text-3xl">$ 1.00 <small
                    class="text-sm">/slice</small></span>
            <span class="block mt-8">
                <p class="text-center tracking-tight font-light text-gray-400">{{food.description}}</p>
            </span>
            <button class="rounded-lg bg-pink-500 text-white px-4 py-2 font-bold mt-6"
                hx-get="#" hx-trigger="click" hx-target="body" hx-swap="innerHTML" hx-push-url="/restaurants/food/{{food.pk}}/"
            >See Details</button>
        </main>
    </div>
</aside>

apps/restaurants/templates/restaurant/food-detail.html
{% comment %} {% extends 'base.html' %}


{% block head %}
<meta name="description" property="og:description" content="{{food.description}}">
<meta name="keywords" content="{{food.name}},{{food.restaurant.name}},iraf {{food.name}} ">
<meta name="author" content="Admin">

<meta property="og:url" content="{{food.get_absolute_url}}"> />
<meta property="og:title" content="{{food.name}}" />
<meta property="og:image" content="{{food.image}}" />
<meta property="og:image:alt" content="{{food.name}}" />

<meta name="twitter:image" content="{{food.image}}" />
<meta property="twitter:image:alt" content="{{food.title}}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="@HeednGrow" />

{% endblock head %}
{% block title %}<title>{{food.title}} from {{food.restaurant}}</title>{% endblock title %}

{% block content %}
<!-- component -->
<section class="text-gray-700 body-font  bg-white">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <img alt="ecommerce" class="lg:w-1/2 w-full object-cover object-center rounded border border-gray-200" src="https://images.food52.com/e6RyxggWQpBwCPcd3kugqz01J54=/2016x1344/filters:format(webp)/583d2633-65c0-43d6-9b52-cba0c8fa1399--2019-1210_nigerian-jollof-rice_3x2_rocky-luten_006.jpg">
        <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">{{food.restaurant.name}}</h2>
          <h1 class="text-green-700 text-3xl title-font font-medium mb-1">{{food.name}} </h1>
          <div class="flex mb-4">
            <span class="flex items-center">
              <div x-data="{ temp: {{food.star}}, orig: {{food.star}} }" class="flex cursor-pointer md:text-4xl">
                <input type="number" :value="orig" class="hidden"/>
              
                <template x-if="orig != null">
                  <span class="text-gray-400 hover:text-gray-700" @mouseenter="temp = null" @mouseleave="temp = orig">{{food.star}}</span>
                </template>
              
                <template x-for="item in [1,2,3,4,5]">
                 <span @mouseenter="temp = item" 
                       @mouseleave="temp = orig"
                       class="text-gray-300"
                       :class="{'text-red-600': ({{food.star|floatformat}} >= item)}">★</span>
                </template>
              </div>
            </span>
            
          </div>
          <p class="leading-relaxed">{{food.description}}</p>
          <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-200 mb-5">
            <div class="flex">
              <span class="mr-3 font-bold uppercase">will you try it?</span>
            </div>
            
          </div>
          <div class="flex">
            <span class="title-font font-medium text-2xl text-gray-900"> &#8358; {{ food.price }}</span>
            <button id="likefood" class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded" 
              hx-post="{% url 'food-try' food.pk %}" hx-trigger="click" hx-target="#likefood" hx-swap="innerHTML"
            >Like</button>
          </div>
        </div>
      </div>
    </div>
    <p class="text-sm uppercase font-bold text-center p-1 text-gray-400">You'll be able to order from your favorite restaurant soon, we're working on it.</p>
  </section>

{% endblock content %}

 {% endcomment %}

apps/restaurants/templates/restaurant/food-list.html
{% extends 'base.html' %}
{% block title %}Foods{% endblock title %}
{% block content %}

<div x-data="{overlay:false}">
    {% comment %} <div x-show="overlay" class="bg-black opacity-50 z-20 top-0 bottom-0 left-0 right-0 fixed" id="overlay"> {% endcomment %}
    </div>
    <p class="text-sm uppercase font-bold text-center p-1 text-gray-400">You'll be able to order from your favorite restaurant soon, we're working on it.</p>

        <div class="mt-8 grid gap-10 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
            
            {% for food in page_obj %}
            <div class="bg-white rounded overflow-hidden shadow-md relative food-item"
                hx-get="{% url 'food' food.restaurant.name food.name  %}" hx-trigger="click" hx-target="body" hx-swap="innerHTML" hx-push-url="/restaurants/food/{{food.pk}}/"> 
                <img src="{{food.image}}" alt="stew" class="w-full h-32 sm:h-48 object-cover">
                <div class="m-4">
                <span class="font-bold" @click="overlay=true">{{food.name}}</span>
                <span class="block text-pink-500 cursor-pointer " hx-get="{% url 'restaurant_detail' food.restaurant.slug %}" hx-target="body">Food from {{food.restaurant}}</span>
                </div>
                <div class="bg-pink-100 text-pink-200 text-xs uppercase font-bold rounded-full p-2 absolute top-0 ml-2 mt-2">
                <span>{{food.discount_price}}</span>
                </div>
            </div>
            {% endfor %}
        </div>
        <div>
            <p class="text-sm uppercase font-bold text-center p-1 mt-2 text-gray-400">You'll be able to order from your favorite restaurant soon, we're working on it.</p>
        </div>
</div>
<div aria-label="Page navigation" class="inline-flex">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="h-10 px-5 text-indigo-600 transition-colors duration-150 bg-white rounded-l-lg focus:shadow-outline hover:bg-indigo-100" hx-get="?page=1" hx-target="body">&laquo; first</a>
            <a class="h-10 px-5 text-white transition-colors duration-150 bg-indigo-600 focus:shadow-outline" hx-get="?page={{ page_obj.previous_page_number }}" hx-target="body">previous</a>
        {% endif %}

        {% if page_obj.has_next %}
            <a class="h-10 px-5 text-indigo-600 transition-colors duration-150 bg-white focus:shadow-outline hover:bg-indigo-100" hx-get="?page={{ page_obj.next_page_number }}" hx-target="body">next</a>
            <a class="h-10 px-5 text-indigo-600 transition-colors duration-150 bg-white focus:shadow-outline hover:bg-indigo-100"  hx-get="?page={{ page_obj.paginator.num_pages }}" hx-target="body">last &raquo;</a>
        {% endif %}
        
        <span class="h-10 px-5 text-indigo-600 transition-colors duration-150 bg-white focus:shadow-outline hover:bg-indigo-100">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
    </span>
</div>
{% endblock content %}

apps/restaurants/templates/restaurant/restaurant-list.html
{% extends 'base.html' %}
{% block title %} Restaurants{% endblock title %}
{% block content %}
<p class="text-sm uppercase font-bold text-center p-1 text-gray-400">You'll be able to order from your favorite restaurant soon, we're working on it.</p>
<div class="container mb-2 flex mx-auto w-full items-center justify-center">
    <div class="flex items-center justify-start mt-4 mb-4">
        {% for category in categories %}
            <a href="#"class="px-2 py-1 font-bold bg-red-400 text-white rounded-lg hover:bg-gray-500 mr-4">{{category}}</a>
        {% endfor %}
    </div>
    <ul class="flex w-5/6 items-center justify-center flex-col p-4">
        {% for restaurant in page_obj %}
            <li class="border-gray-400  m-6 w-full flex flex-row"
            hx-get="{% url 'restaurant_detail' restaurant.slug %}" hx-trigger="click" hx-target="body" hx-swap="innerHTML" hx-push-url="{% url 'restaurant_detail' restaurant.slug%}"
            >
                <div class="select-none flex flex-1 items-center transition duration-500 ease-in-out transform hover:-translate-y-2 rounded-2xl border-2 p-6 hover:shadow-2xl border-pink-400">
                    <div class="flex-1 pl-1 mr-16">
                        <div class="font-medium text">
                            {{restaurant.name}}
                        </div>
                    </div>
                    <div class="text-wrap text-center flex text-white text-sm md:text-bold flex-col rounded-md bg-pink-500 justify-center items-center p-2">
                        <p class="block">
                            <div x-data="{ temp: 2, orig: 2 }" class="flex cursor-pointer text-xl md:text-4xl">
                                <input type="number" :value="orig" class="hidden"/>
                              
                              
                                <template x-for="item in [1,2,3,4,5]">
                                 <span @mouseenter="temp = item" 
                                       @mouseleave="temp = orig"
                                       class="text-gray-300"
                                       :class="{'text-red-600': ({{restaurant.review}} >= item)}">★</span>
                                </template>
                              </div>
                        </p>
                        <p class="block">
                            {{ restaurant.num_reviews }} users
                        </p>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
<div aria-label="Page navigation" class="inline-flex">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="h-10 px-5 text-indigo-600 transition-colors duration-150 bg-white rounded-l-lg focus:shadow-outline hover:bg-indigo-100" hx-get="?page=1" hx-target="body">&laquo; first</a>
            <a class="h-10 px-5 text-white transition-colors duration-150 bg-indigo-600 focus:shadow-outline" hx-get="?page={{ page_obj.previous_page_number }}" hx-target="body">previous</a>
        {% endif %}

        {% if page_obj.has_next %}
            <a class="h-10 px-5 text-indigo-600 transition-colors duration-150 bg-white focus:shadow-outline hover:bg-indigo-100" hx-get="?page={{ page_obj.next_page_number }}" hx-target="body">next</a>
            <a class="h-10 px-5 text-indigo-600 transition-colors duration-150 bg-white focus:shadow-outline hover:bg-indigo-100"  hx-get="?page={{ page_obj.paginator.num_pages }}" hx-target="body">last &raquo;</a>
        {% endif %}
        
        <span class="h-10 px-5 text-indigo-600 transition-colors duration-150 bg-white focus:shadow-outline hover:bg-indigo-100">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
    </span>
</div>
<p class="text-sm uppercase font-bold text-center p-1 text-gray-400">You'll be able to order from your favorite restaurant soon, we're working on it.</p>

{% endblock content %}

apps/restaurants/templates/restaurant/restaurant.html
{% extends 'base.html' %}


{% block head %}
<meta name="description" property="og:description" content="{{restaurant.description}}">
<meta name="keywords" content="restaurant in {{restaurant.location}}, iraf {{restaurant.name}},{{restaurant.name}}">
<meta name="author" content="Admin Iraf">

<meta property="og:url" content="{{restaurant.get_absolute_url}}"> />
<meta property="og:title" content="{{restaurant.name}}" />
<meta property="og:image" content="{{restaurant.image}}" />
<meta property="og:image:alt" content="restaurant.description" />

<meta name="twitter:image" content="{{restaurant.image}}" />
<meta property="twitter:image:alt" content="{{restaurant.name}}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="@HeednGrow" />

{% endblock head %}
{% block title %}<title>{{restaurant.name}}</title>{% endblock title %}

{% block content %}
<section class="text-gray-700 body-font  bg-white">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <img alt="ecommerce" class="lg:w-1/2 w-full object-cover object-center rounded border border-gray-200" src="https://images.food52.com/e6RyxggWQpBwCPcd3kugqz01J54=/2016x1344/filters:format(webp)/583d2633-65c0-43d6-9b52-cba0c8fa1399--2019-1210_nigerian-jollof-rice_3x2_rocky-luten_006.jpg">
      <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">{{restaurant.location}}</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{restaurant.name}} </h1>
        <div class="flex mb-4">
          <span class="flex items-center">
            <div x-data="{ temp: 5, orig: 0 }" class="flex cursor-pointer md:text-4xl">
              {% comment %} <input type="number" :value="orig" class="hidden"/>
            
              <template x-if="orig != null">
                <span class="text-gray-400 hover:text-gray-700" @mouseenter="temp = null" @mouseleave="temp = orig">{{food.star}}</span>
              </template> {% endcomment %}
            
              <template x-for="item in [1,2,3,4,5]">
               <span class="text-gray-300"
                     :class="{'text-red-600': ({{restaurant.rating|floatformat}} >= item)}">★</span>
              </template>
            </div>
          </span>
          
        </div>
        <p class="leading-relaxed">{{restaurant.description}}</p>
        <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-200 mb-5">
          
        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl text-gray-900">{{restaurant.like.count}} <span class="text-bold uppercase content-center text-pink-500">Likes</span></span>
          <button id="like" class="flex ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded"
            hx-post="{% url 'restaurant-like' restaurant.pk %}" hx-trigger="click" hx-target="#like" hx-swap="innerHTML" 
            >Like</button>
        </div>
      </div>
    </div>
    <p class="text-sm uppercase font-bold text-center p-1 mt-2 text-gray-400">You'll be able to order from your favorite restaurant soon, we're working on it.</p>

  </div>
  {% comment %} adding reviews and analysis {% endcomment %}
  {% include 'restaurant/partials/reviews.html' %}

</div>

<p class="text-sm uppercase font-bold text-center p-1 text-gray-400">You'll be able to order from your favorite restaurant soon, we're working on it.</p>

{% comment %} menu {% endcomment %}
{% include 'restaurant/partials/menu.html' %}

{% comment %} review detail {% endcomment %}
{% include 'restaurant/partials/review_list.html' %}

{% endblock content %}